#+TITLE: Seminar 3: Legal Regulation of Authorship and Moral Rights
#+AUTHOR: Chen Zhu (Birmingham Law School) 
#+PANDOC_OPTIONS: number-sections:nil 
#+PANDOC_OPTIONS: standalone:t
#+roam_alias:
#+roam_tags: "seminar sheet" "git repo"
#+keywords: "seminar sheet" "git repo"



* Introduction
This seminar looks at why and how “authorship” functions as an organising concept in relation to copyright ownership. It explores many puzzles about authors' moral rights as opposed to their economic rights in an international context.

* Seminar Questions

** [Q1] The Monkey Selfie Dispute  
Is the British wildlife photographer Mr. David Slater entitled to the copyright of the selfie photographs taken by an Indonesian monkey who “used” Slater's equipment? What is the dispute between Slater and the Wikimedia Foundation? Does Slater's claim further stretch the
boundary of the IP law and can it be justified?

** [Q2] Joint Authorship 
What are the main requirements of joint authorship under UK law? Why did the claimant fail to fulfil these requirements in /Brighton v Jones/? In contrast, why was Matthew Fisher able to a legally recognised joint author in /Fisher v Brooker/?

** [Q3] Moral Rights and the Berne Convention 
What are the two moral rights as identified under the Berne Convention Article 6bis? How long do moral rights last? Does the British copyright law fully incorporate these two moral rights into the CDPA?

** [Q4] Derogatory Treatment
What is the meaning of "derogatory treatment" in relation to the breach of authorial integrity? Is "treatment" under Section 80 the same as "adaption" under Section 21 of CDPA? What is meant by "derogatory"?

** [Q5] Canadian Connection
What is the Canadian Case /Snow v Eaton Centre/ about? What is its connection with UK moral right of integrity?

** [Q6] Beyond Berne
Apart from the two Berne moral rights, UK copyright also has an indigenous moral right. What is it and what is unique about it?

** [Q7] Ghostwriting
What is ghostwriting? What are potential moral right issues behind ghost writing?
- See 2 real examples of ghostwriting: i) the Japanese “Beethoven” scandal:
[[http://www.newyorker.com/culture/culture-desk/the-unmasking-of-japans-beethoven][http://www.newyorker.com/culture/culture-desk/the-unmasking-of-japans-beethoven]]
- The legal dispute concerning the former German Chancellor Helmut Kohl's ghostwritten memoir:
[[http://ipkitten.blogspot.co.uk/2014/11/mr-kohl-and-his-ghostwriter-regional.html][http://ipkitten.blogspot.co.uk/2014/11/mr-kohl-and-his-ghostwriter-regional.html]]

** [Q8] Shostakovitch's Claim
Could the Soviet composer Shostakovitch claim his moral right in his music, which was used, without his approval, in an anti-Soviet movie made in the U.S.? How are moral rights protected in the USA today?


* Seminar Readings
** Legal Regulation of Authorship 
- Jane Ginsburg, ‘The Concept of Authorship in Comparative Copyright Law' (2002-2003) 52 Depaul L Rev 1063
  + Note the 6 principles of authorship across the 6 jurisdictions as discussed by Ginsburg
  + this article also provides important ammunition for UK judges to make the ruling in /Sawkins v Hyperion.

** Monkey "selfie"
- *Andres Guadamuz, “The Monkey Selfie: Copyright Lessons for Originality in Photographs and Internet Jurisdiction” (2016) 5 (1) Internet Policy Review

- Annemarie Bridy, “Coding Creativity: Copyright and the Artificially Intelligent Author” (2012) Stanford Technology Law Review 5

** Joint authorship

- Section 10, CDPA, 1988

- *Brighton v Jones [2004] EWHC1157 (Ch); [2004] EMLR 507

- *Fisher v Brooker [2009] UKHL 41 [quickly skim the ruling and try to find the part that enables you to answer the relevant seminar question.]

- Richard Arnold, ‘Reflections on "The Triumph of Music": copyrights and performers' rights in music' [2010] IPQ 153
 
** Moral rights and authorship
- J Griffiths, “Not Such a ‘Timid Thing': The United Kingdom's Integrity Right and Freedom of Expression” in Copyright and Free Speech U.Suthersanen (eds), pp. (OUP, 2005) pp.211-244 at  [[http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1476825][http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1476825]]

- Elizabeth Adeney, ‘The moral right of integrity: the past and future of honour' [2005] IPQ 111

- Edward J. Damich, “The Right of Personality: A Common--Law Basis for the Protection of the Moral Rights of Authors” (1988) 23 Ga. L. Rev.1-96

- Lionel de Souza and Charlotte Waelde, “Moral Rights and the Internet: squaring the circle” (2002) 3 I.P.Q 265-288

- Adolf Dietz, “The moral right of the author: moral rights and the civil law countries” (1994) 19 Colum.-VLA JL & Arts 199-227

- Gerald Dworkin, “The Moral Right of the Author: Moral Rights and the  Common Law Countries” (1995) 19 Colum.-Vla JL & Arts 229.

- Henry Hansmann and Santilli Marina, “Authors' and artists' moral rights: A comparative legal and economic analysis” (1997) 26(1) The Journal of Legal Studies 95-143

- Roberta Rosenthal Kwall, “Preserving Personality and Reputational Interests of Constructed Personas Through Moral Rights: A Blueprint for the Twenty-First Century” (2001) U. Ill. L. Rev. 151-172

- Susan P. Liemer, “On the Origins of Le Droit Moral: How Non-Economic Rights Came to Be Protected in French IP Law” (2011) 19 J. Intell. Prop. L. 65

- *Cyrill P. Rigamonti, “The conceptual transformation of moral rights” (2007) 55(1)The American journal of comparative law 67-122

- Martin A. Roeder, ‘The Doctrine of Moral Right: A Study in the Law of Artists, Authors, and Creators' [1940] 53 Harvard Law Review 554

- Dan Rosen, “Artists' Moral Rights: A European Evolution, An American Revolution” (1983) 2 Cardozo Arts & Ent. LJ 155-188

- Craig A. Wagner, “Motion picture colorization, authenticity, and the elusive moral right” (1989) 64 NYUL Rev. 628-725

** Moral right and trade marks
- Jane C. Ginsburg, “The Author's Name as a Trademark: A Perverse Perspective on the Moral Right of Paternity” (2005) 23 Cardozo Arts & Ent. LJ 379-389

- Greg Lastowka, "Digital Attribution: Copyright and the Right to Credit" (2007) 87 BUL Rev. 41-89

** Copyright, authorship and open-source

- Section 9, CDPA, 1988
- *P Jaszi, "Toward a theory of Copyright: The Metamorphoses of 'Authorship'" [1991] Duke Law Journal 455

- Severine Dusollier, ‘Open Source and Copyleft: Authorship Reconsidered?' (2003) 26 Columbia Journal of Law and the Arts 283

- CW Zhu, ‘A Regime of Droit Moral Detached from Software Copyright?---The Undeath of the “Author” in Free and Open Source Software Licensing” (2014) 22 (4) Int J Law Info Tech 367-392

- Aurelija Lukoševičienė, “On Author, Copyright and Originality: Does the Unified EU Originality Standard Correspond to The Digital Reality  in Wikipedia?” [2017] 11 (2) Masaryk University Journal of Law and Technology 215

** Authorship and Ownership

- Cummins v Bond [1927] 1 Ch 167 (concerning a work called “The Chronicle of Cleophas”)

- Leah v Two Worlds Publishing Ltd [1951] Ch 393

- *Ray v Classic FM Plc/ [1998] FSR 622

- Beckingham v Hodgens [2003] All ER (D) 247; [2003] EWCA Civ 143

** Moral rights legislation (UK & International)*

- Article 6bis, Berne Convention

- Sections 77-84, CDPA, 1988

** Attribution & Integrity
-  Morrison Leahy Music Ltd v Lightbody Ltd [1993] EMLR 144

-  *Tidy v The Trustees of the Natural History Museum (1995) 37 IPR 501 (UK); (1996) 2 Entertainment Law Review E27
  
- Pasterfield v Denham [1999] FSR 168
  
- *Confetti Records v Warner Music UK Ltd [2003] EMLR 35

- Delves-Broughton v House of Harlot Ltd [2012] EWPCC 29
  
- Sawkins v Hyperion [2005] RPC 32 (CA) (right of attribution)

- *Snow v Eaton Centre Ltd (1982) 70 CPR (2d) 105 (Ont.) (Canada)

** False Attribution

- Moore v News of the World [1972] 1 QB 441 (first UK false  attribution case)

- Noah v Shuba [1991] FSR 14

- Clark v Associated Newspapers [1998] 1 WLR 1558; 1 All ER 959

- Harrison v Harrison [2010] E.C.D.R. 12

** Canadian Connection

- Section 28 , Copyright Act of Canada
  + pay particular attention to Section 28.2 (1), which defines the scope of the author's or performer's right of integrity
  + find out how does UK law differs from Canadian law in this regard

#+BEGIN_QUOTE
*Nature of right of integrity*
28.2 (1) The author’s or performer’s right to the integrity of a work or performer’s performance is infringed only if the work or the performance is, to the prejudice of its author’s or performer’s honour or reputation,
        (a) distorted, mutilated or otherwise modified; or
        (b) used in association with a product, service, cause or institution.

    [Marginal note:Where prejudice deemed]

    (2) In the case of a painting, sculpture or engraving, the prejudice referred to in subsection (1) shall be deemed to have occurred as a result of any distortion, mutilation or other modification of the work.

    [Marginal note:When work not distorted, etc.]

    (3) For the purposes of this section,

        (a) a change in the location of a work, the physical means by which a work is exposed or the physical structure containing a work, or
        (b) steps taken in good faith to restore or preserve the work

shall not, by that act alone, constitute a distortion, mutilation or other modification of the work.
#+END_QUOTE

** "Moral Rights" in the US 
- 17 U.S.C. §101, Visual Artists Rights Act (VARA), 1990, US

- *Shostakovich v. Twentieth Century-Fox Film
  Corp., 80 N.Y.S.2d 575 (N.Y. Sup. Ct. 1948), aff'd, 87 N.Y.S.2d 430 (N.Y. App. Div. 1949) (concerning the film /The Iron Curtain/) also available  [[http://www.leagle.com/decision/1948263196Misc67_1247/SHOSTAKOVICH v. TWENTIETH CENTURY-FOX FILM CORP][http://www.leagle.com/decision/1948263196Misc67_1247/SHOSTAKOVICH%20v.%20TWENTIETH%20CENTURY-FOX%20FILM%20CORP]]

- Gillian v ABC 538 F.2d 14 (2nd Cir. 1976) (the Monty Python case)

- Dastar v. 20th Century Fox (2003) 539 US 23 (reverse passing off)]


* pandoc export to pdf                                             :noexport:
Chen's Note: the below =pandoc= command is for exporting the seminar sheet into a PDF document. It is tagged with =:noexport:=. The command is stored in an org-babel block, which can be executed by typing =Ctrl-c= twice. This will send the PDF file to your =~/Desktop= directory.  
#+BEGIN_SRC sh
pandoc seminar3*.org -o ~/Desktop/seminar3.pdf --pdf-engine=xelatex
#+END_SRC

#+RESULTS:
